trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: git submodule update --init --recursive
- task: UseDotNet@2
  inputs:
    version: '6.x'
    includePreviewVersions: true

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration Release
  displayName: 'Build'

- script: dotnet publish -c Release -r linux-x64 --self-contained true
  displayName: 'Publish'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'console-app'
    targetPath: '$(Build.ArtifactStagingDirectory)'